### ISSUE TITLE
segfault when I move the mouse arround the sublime application

### ISSUE THREAD

**Issue by borsanza** [snapcrafters/sublime-text#11]
syslog:
    kernel: [16223.221138] sublime_text[19585]: segfault at 50 ip 00007fed55ca273c sp 00007ffe05f75b80 error 4 in ld-2.23.so[7fed55c96000+26000]

I am using Ubuntu Mate 18.04

**Comment by om26er** [comment]
We can close this bug as it was caused by elf patching, which is now disabled.

**Comment by om26er** [comment]
This has been fixed for a while. Closing
