### ISSUE TITLE
Dev channel support

### ISSUE THREAD

**Issue by kyluca** [snapcrafters/sublime-text#14]
Hey @om26er, love your work!

I just want to clarify if using the dev channel (https://www.sublimetext.com/3dev) is possible via this snap? I've seen [your discussion with Will Bond on the official forums](https://forum.sublimetext.com/t/modern-instalation-snap-package/31123/4), but maybe the dev channel idea hasn't been implemented yet?

It looks like the --edge snap channel installs the latest stable version (3170, previously 3143) at the moment:

![selection_1999](https://user-images.githubusercontent.com/17324842/39726784-9508b2da-5293-11e8-9b4c-b3b03187a280.png)

As a licensed user, I would love to be able to use this snap for Sublime Text's dev channel (e.g. 3168, 3169, 3171 once it's out) so I can stay up to date with the bleeding-edge.

Cheers,
Kyle

**Comment by om26er** [comment]
We could probably have a totally different snap, named sublime-text-dev to follow the dev releases instead.

**Comment by kyluca** [comment]
Hmm yeah that could be one workaround but perhaps not the ideal solution?

It seems that [the snap channels](https://docs.snapcraft.io/reference/channels) are designed to let us use one package name with multiple version options (stable vs. beta/dev etc).

I might give this a go soon (unless someone beats me to it haha) :grin:

**Comment by kyluca** [comment]
Just put up a quick PR with my thoughts #15 :smile:

**Comment by 3v1n0** [comment]
More than a different snap, I'd prefer to add a different version track for this, so that users can just follow dev track

**Comment by kyluca** [comment]
Yeah @3v1n0 that's my hope too, [bit more of a recent discussion](https://github.com/snapcrafters/sublime-text/pull/15#issuecomment-423850662) over on this Pull Request #15

**Comment by jnsgruk** [comment]
We could probably get this going in a similar way to the `gimp` snap, where we have the `preview` branch.

**Comment by jnsgruk** [comment]
This is now done! You should be able to `sudo snap install sublime-text --classic --channel dev/stable`
