### ISSUE TITLE
Ship libgtk2.0-0 with the snap

### ISSUE THREAD

**Issue by om26er** [snapcrafters/sublime-text#19]
In Ubuntu 18.10 it seems libgtk2.0-0 is not installed by default. That causes sublime to not start unless gtk is installed manually

**Comment by om26er** [comment]
Update: it seems we do ship libgtk2.0-0 with this snap but due to whatever reason the snap isn't able to satisfy its runtime dependencies.

Investigating...

**Comment by wbond** [comment]
Dev builds 3181+ use GTK3, just an FYI for future planning.
