### ISSUE TITLE
Cannot using ibus-pinyin on snap version of sublime

### ISSUE THREAD

**Issue by lostncg** [snapcrafters/sublime-text#21]
This is a common issue on snap apps, the Chinese input method is selected but not working on it.
Here is a post which could help in fixing this issue, please refer
https://forum.snapcraft.io/t/failed-to-input-chinese-in-many-snap-apps/7251

**Comment by merlijn-sebrechts** [comment]
Can you test if this issue is still present in the latest version? We've had a lot of releases since then.

**Comment by jnsgruk** [comment]
Closing this as more information is required. @lostncg if you're able to test the later releases and they don't solve your problem, I'm happy to reopen and investigate. Thanks!
