### ISSUE TITLE
Incorrect Dependencies for Build 3181

### ISSUE THREAD

**Issue by wbond** [snapcrafters/sublime-text#23]
In dev build 3181 we switched to GTK3. The snap does not seem to have been updated for this.

 - https://www.sublimetext.com/3dev
 - https://github.com/snapcrafters/sublime-text/blob/539273f53ef7056f18fa5e6c1cf0f744c5703650/snap/snapcraft.yaml#L67

**Comment by popey** [comment]
Thanks for the notification @wbond - we're only building the stable build, currently 3176. When will the next stable release go out which uses GTK3? We can nudge the dependency on the next build so as soon as you release, the snap store will get the correctly built version.

**Comment by wbond** [comment]
So what is the deal with the “edge” version on the site that was built on Feb 12?

**Comment by popey** [comment]
It's just a rebuild of the existing snap which supplies the stable release. We could certainly modify the snap build setup to pull both stable and dev builds and stable ones.

Do Sublime Text users typically install both stable and dev builds side by side? is the application appropriately namespaced to separate configuration etc in two different places?
