### ISSUE TITLE
The sublime-text desktop file is malformed

### ISSUE THREAD

**Issue by kapad** [snapcrafters/sublime-text#24]
```
[Desktop Entry]
X-SnapInstanceName=sublime-text
Version=1.0
Type=Application
Name=Sublime Text
GenericName=Text Editor
Comment=Sophisticated text editor for code, markup and prose
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/sublime-text_subl.desktop /snap/bin/sublime-text.subl %U
Terminal=false
MimeType=text/plain;
Icon=/snap/sublime-text/58/opt/sublime_text/Icon/256x256/sublime-text.png
Categories=TextEditor;Development;
StartupNotify=true
Actions=Window;Document;

[Desktop Action Window]
Name=New Window

[Desktop Action Document]
Name=New File
```

For `[Desktop Action Window]` the line `env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/sublime-text_subl.desktop /snap/bin/sublime-text.subl -n %U` needs to be added at the bottom of the section. 

Also, I think `[Desktop Action Document]` section can be dropped, because opening a new file is handled by the `%U` in the main, `[Desktop Entry]` section.

**Comment by merlijn-sebrechts** [comment]
Thanks for reporting! This has been fixed in the latest version.
