### ISSUE TITLE
`snap run sublime-text` doesn't work

### ISSUE THREAD

**Issue by Gotterbild** [snapcrafters/sublime-text#25]
First of all, thanks for a snap version of Sublime Text!

When I run `snap run sublime-text` I get this error:
`cannot find app "sublime-text" in "sublime-text"`

It took me a time and effort to understand that I need to run 
`snap run sublime-text.subl`

Maybe change 
https://github.com/snapcrafters/sublime-text/blob/7781290d70674bf17dc41db7d22d1e3c7516c56b/snap/snapcraft.yaml#L16
to
  `sublime-text:`
or
`  'sublime-text':`
?

I would propose a Pull Request, but I don't know how to test if this change will work. That is why I decided to post an issue.

**Comment by popey** [comment]
What if you just run `subl`?

Also, what is the output of `snap version`

**Comment by Gotterbild** [comment]
If I run `snap run subl`
I get
`cannot find current revision for snap subl: readlink /snap/subl/current: no such file or directory`

Output of `snap version` is:
```
snap    2.38
snapd   2.38
series  16
ubuntu  18.04
kernel  4.18.0-17-generic
```

**Comment by om26er** [comment]
You should just use the command `subl`, no need for `snap run subl`. I do think that we may need to have a new entry point that's just `sublime-text`, for that we only need to change that line https://github.com/snapcrafters/sublime-text/blob/master/snap/snapcraft.yaml#L16 to `sublime-text`

**Comment by popey** [comment]
Huh, you're right. I mean, `snap run subl` should work in my book, but `subl` is more accurate as you say.

**Comment by Gotterbild** [comment]
Thanks guys. However, I still have another problem. I'll create a separate issue for that.

**Comment by om26er** [comment]
Closing, as the original reporter no longer faces the issue.
