### ISSUE TITLE
Sublime Text 4

### ISSUE THREAD

**Issue by jwillikers** [snapcrafters/sublime-text#30]
Would it be possible to add support for Sublime Text 4 which is currently under development? Packages are released regularly and mentioned on [their Discord server](https://forum.sublimetext.com/t/sublime-text-discord-server/26063) in the *announcements* channel. They've also been publishing Sublime Text 4 packages for 64-bit ARM on Linux, which would be great to have access to as a snap.

**Comment by om26er** [comment]
So I just looked around and seems they don't advertise that anywhere on their site. However I did find the build in the `announcements` channel as you pointed. Following the previous pattern I think it may make sense to publish a separate snap for sublime-text 4. It's quite likely they will continue to support sublime text 3 for a long time, just like they did with version 2. Need to check with the upstream though.

**Comment by om26er** [comment]
It also seems that the new version requires a license and no way to start with without one.

**Comment by jwillikers** [comment]
@om26er Yes, the development builds of Sublime Text 4 require a license if you want to use them.

They haven't released any updates for Sublime Text 3 in while, so I'm not sure what their transition plan will be. So long as they are supporting Sublime text 3 and 4 simultaneously, I would think separate snaps sound like a good idea.

Could there be problems if Sublime Text 4 uses the same user configuration files as Sublime Text 3? Currently the path `~/.config/sublime-text-3` is still used by Sublime Text 4 though I don't know whether this will change in the future. User's wishing to install both the Sublime Text 3 and Sublime Text 4 snaps may have to share configuration between both versions.

**Comment by jwillikers** [comment]
Having a separate Snap for Sublime Text 4 also presents an issue for the `subl` alias, which both Sublime Text 3 and 4 users would expect to use. The problem is that only one snap can claim that namespace.

**Comment by limpid-kzonix** [comment]
Already released, would be nice to see the snap for version 4

**Comment by juuh42dias** [comment]
Something update?

**Comment by chrwahl** [comment]
Can channels be added, so that you can switch between or select the version you need?

**Comment by aradapilot** [comment]
4 is stable now, so this should be simpler than the dual channel approach (but a subl-dev or something for future releases could work?)
looking forward to it!
