### ISSUE TITLE
“Open Folder” doesn't work

### ISSUE THREAD

**Issue by martinstuecklschwaiger** [snapcrafters/sublime-text#31]
Opening a folder doesn't work. 

**How to reproduce this**
* Click `File` / `Open Folder…` and open a folder

**Alternative**
* Type `subl .` 

**What happens**
The directory won't be opened in Sublime. Instead a new window will open with an empty new file.

**What should happen**
Sublime should open the directory.

**Comment by martinstuecklschwaiger** [comment]
**Sublime version**
`snap info sublime-text`
```
name:      sublime-text
summary:   A sophisticated text editor for code, markup and prose.
publisher: Snapcrafters
store-url: https://snapcraft.io/sublime-text
contact:   https://github.com/snapcrafters/sublime-text/issues
license:   unset
description: |
  A sophisticated text editor for code, markup and prose.
  
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - sublime-text.subl
snap-id:      2kOIsSRmQ7zjpIxzZDpoXaZOVejqaGOT
tracking:     latest/stable
refresh-date: today at 11:11 CET
channels:
  latest/stable:    3211 2020-12-04  (97) 59MB classic
  latest/candidate: ↑                          
  latest/beta:      ↑                          
  latest/edge:      3211 2021-02-26 (100) 59MB classic
installed:          3211             (97) 59MB classic
```

**Snap version**
`snap version`
```
snap    2.49
snapd   2.49
series  16
ubuntu  20.10
kernel  5.8.0-45-generic
```

**Comment by popey** [comment]
How odd. I use this feature every day. I am completely unable to reproduce this. When I run `subl .` I get a new window in which a folder view shows the files in the current directory.

Looks like this:

![Screenshot_20210322_202509](https://user-images.githubusercontent.com/1841272/112053852-c7c0aa80-8b4c-11eb-92ac-7aaf14b2a368.png)
