### ISSUE TITLE
Sublime Text 4121 Is Out

### ISSUE THREAD

**Issue by om26er** [snapcrafters/sublime-text#36]
Working on it, will do a call for testing on the forum and post a link here.

**Comment by stevencrader** [comment]
What is the timeline for getting the update via snap?

**Comment by om26er** [comment]
@stevencrader The latest version is in the dev channel (snap refresh sublime-text --edge), we should move it to stable channel soonish. Your feedback is welcome

**Comment by merlijn-sebrechts** [comment]
This has been released to stable, thanks @om26er!
