### ISSUE TITLE
[Bug]: Cannot start sublime-text snap

### ISSUE THREAD

**Issue by RJDan** [snapcrafters/sublime-text#38]
### What happened?

I removed the PPA app and installed the stable snap with the ```--classic``` flag as snap said I should.
Installation was successful.
When trying to start sublime-text from the CLI with ```subl``` I get an error:
```
/ not root-owned 1000:0
```
and nothing else happens.
I have tried with the edge version as well and got the same result.

I am using sway version 1.7
Wayland
Ubuntu 22.04
ASUSTeK COMPUTER INC. ASUS TUF Gaming A15 FA506IH_FA506IH/FA506IH, BIOS FA506IH.316 03/12/2021

### What should have happened?

The sublime gui should have opened.

### Output of `snap info $snap_name`

```shell
name:      sublime-text
summary:   A sophisticated text editor for code, markup and prose.
publisher: Snapcrafters
store-url: https://snapcraft.io/sublime-text
contact:   https://github.com/snapcrafters/sublime-text/issues
license:   unset
description: |
  A sophisticated text editor for code, markup and prose.
commands:
  - sublime-text.subl
snap-id:      2kOIsSRmQ7zjpIxzZDpoXaZOVejqaGOT
tracking:     latest/stable
refresh-date: today at 12:36 CET
channels:
  latest/stable:    4126 2021-12-22 (112) 68MB classic
  latest/candidate: ↑                          
  latest/beta:      ↑                          
  latest/edge:      4126 2021-12-21 (112) 68MB classic
installed:          4126            (112) 68MB classic
```

### Output of `snap connections $snap_name`

```shell
Nothing is printed.
```

### Output of `snap version`

```shell
snap    2.56
snapd   2.56
series  16
ubuntu  22.04
kernel  5.15.0-39-generic
```

### Relevant log output

```shell
I am not sure what a relevant output would look like.
```

### Teminal output of app

```shell
/ not root-owned 1000:0
```

**Comment by diddledani** [comment]
This is not an issue with the Sublime Text snap. Your root folder on your filesystem is owned by the user with ID 1000. This is very unusual for a Linux installation and snapd requires that it not be the case. You need to execute `chown root:root /` before it will launch your snap.

**Comment by RJDan** [comment]
Thanks! I corrected that and it is now working.
