### ISSUE TITLE
File Manager not opening files correctly when Sublime is the default editor

### ISSUE THREAD

**Issue by Josephvb10** [snapcrafters/sublime-text#4]
I use Arch with the Deepin DE. I noticed that when I select the Snap Sublime as the default text editor, when double-clicking a text file in the file manager, Sublime doesn't open the file correctly (it just displays a blank file).

I fixed it myself by changing line 7 in the .desktop file from:

`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/sublime-text-3_sublime-text-3.desktop /var/lib/snapd/snap/bin/sublime-text-3 %U`

to

`Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/sublime-text-3_sublime-text-3.desktop /var/lib/snapd/snap/bin/sublime-text-3 %F`

**Comment by flexiondotorg** [comment]
The is fixed upstream and in the snap via #13
