### ISSUE TITLE
[Enhancement]: Update to 4152

### ISSUE THREAD

**Issue by jymbob** [snapcrafters/sublime-text#43]
### What changes would you like?

SublimeText is prompting me to update, but there's no update available for this snap package. This is somewhat frustrating, as it's telling me every time I open the application.

Pretty please?

**Comment by lucyllewy** [comment]
Hi,

I've just released the latest version. You can either let the Snap service automatically update you when it notices the change, or you can make it update with this command in the terminal:

```bash
sudo snap refresh sublime-text
```
