### ISSUE TITLE
[Bug]: libmd.so.0 not available for sublime-text. Ubuntu 20.04 Sublime 4166

### ISSUE THREAD

**Issue by dagbj** [snapcrafters/sublime-text#47]
### What happened?

Sublime-text does not start. Starting from command line gives this error:
`$ subl
/snap/sublime-text/130/opt/sublime_text/sublime_text: error while loading shared libraries: libmd.so.0: cannot open shared object file: No such file or directory
`
I used sublime just the other day.

Digging around this problem, I find some reports that might be relevant:
https://forum.snapcraft.io/t/classic-base-core22-snap-not-finding-libraries-from-base/35192

Trying the test specified there I do not get much further:
`$ snap run --shell subl
error: cannot find current revision for snap subl: readlink /snap/subl/current: no such file or directory
`
Please note that I'm running on Ubuntu 20.04. Upgrading the OS is not possible for me. I did a remove and install. Which did not help.

### What should have happened?

I should have got a running sublime text.

### Output of `snap info $snap_name`

```shell
$ snap info sublime-text
name:      sublime-text
summary:   A sophisticated text editor for code, markup and prose.
publisher: Snapcrafters✪
store-url: https://snapcraft.io/sublime-text
contact:   https://github.com/snapcrafters/sublime-text/issues
license:   Proprietary
description: |
  Sublime Text is a powerful multi-platform text editor with a clean, modern user interface.
  Bringing wide support for programming languages, extensions, syntax-based features and many other
  useful features alongside low resource usage, Sublime Text proves itself to be a very competent
  solution for a vast set of environments and applications.
  The software may be downloaded and evaluated for free, however a license must be purchased for
  continued use.
  
    **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - sublime-text.subl
snap-id:      2kOIsSRmQ7zjpIxzZDpoXaZOVejqaGOT
tracking:     latest/stable
refresh-date: today at 15:57 CET
channels:
  latest/stable:    4166 2023-11-22 (130) 62MB classic
  latest/candidate: ↑                          
  latest/beta:      ↑                          
  latest/edge:      4166 2023-11-22 (130) 62MB classic
installed:          4166            (130) 62MB classic
```

### Output of `snap connections $snap_name`

```shell
$ snap connections sublime-text
```

### Output of `snap version`

```shell
$ snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  20.04
kernel  5.15.0-88-generic
```

### Relevant log output

```shell
After boot, just some messages regarding JFS and btrfs
```

### Teminal output of app

```shell
$ subl
/snap/sublime-text/130/opt/sublime_text/sublime_text: error while loading shared libraries: libmd.so.0: cannot open shared object file: No such file or directory
```

**Comment by nmondal** [comment]
Facing the exact same problem.

**Comment by raimopinding** [comment]
Same here...

**Comment by sarathkumar006** [comment]
me too facing this issue.i uninstalled it with snap. and followed this steps. sublime working for me
https://www.sublimetext.com/docs/linux_repositories.html

**Comment by raimopinding** [comment]
Thank you sarathkumar006, i did the same and it worked and yes, unsaved files are not lost.

**Comment by tahsinkose** [comment]
If you want to keep using sublime-text with snap, you can revert to the previous stable version of it. Do the following: 

1. `snap list sublime-text --all` to see the versions you have locally.
2. `sudo snap revert sublime-text --revision <an_older_revision>` -- you need to specify the number from `Rev` field as `<an_older_revision>`, not from `Version` field.

**Comment by om26er** [comment]
I think we will revert the latest revision

**Comment by om26er** [comment]
It would be interesting to check if installing `libmd0` on the host fixes the issue? `sudo apt-get -y install libmd0`

**Comment by dafcioo** [comment]
> sudo apt-get -y install libmd0

Ubuntu 20.04, it leads to another errors:

/snap/sublime-text/130/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/130/usr/lib/x86_64-linux-gnu/libX11.so.6)
/snap/sublime-text/130/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/sublime-text/130/usr/lib/x86_64-linux-gnu/libX11.so.6)
/snap/sublime-text/130/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/130/usr/lib/x86_64-linux-gnu/libXau.so.6)
/snap/sublime-text/130/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/130/usr/lib/x86_64-linux-gnu/libbsd.so.0)

**Comment by om26er** [comment]
I have a PR up for a revert https://github.com/snapcrafters/sublime-text/pull/49 -- we will figure out a proper fix afterwards

**Comment by popey** [comment]
Thanks for reporting this issue. A new build of sublime-text is now in the `candidate` channel which aims to fix this. Could anyone who has been affected by this please test.

`snap refresh sublime-text --candidate`

You'll get revision 132 on x86 and 133 on arm computers.

If that's resolved, we'll move it to the stable channel. Thanks again, and apologies for the inconvenience!

**Comment by dafcioo** [comment]
> Thanks for reporting this issue. A new build of sublime-text is now in the `candidate` channel which aims to fix this. Could anyone who has been affected by this please test.
> 
> `snap refresh sublime-text --candidate`
> 
> You'll get revision 132 on x86 and 133 on arm computers.
> 
> If that's resolved, we'll move it to the stable channel. Thanks again, and apologies for the inconvenience!

On my Ubuntu 20.04 it does not, unfortunately. Looks like libmd0 needs newer GLIBC (I have 2.31 on my machine):

/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libX11.so.6)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libX11.so.6)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libXau.so.6)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libbsd.so.0)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libmd.so.0)

**Comment by popey** [comment]
@dafcioo Thanks. That makes no sense :exploding_head: - how are you running sublime-text? Can you `/snap/bin/sublime-text.subl`

**Comment by dafcioo** [comment]
> @dafcioo Thanks. That makes no sense 🤯 - how are you running sublime-text? Can you `/snap/bin/sublime-text.subl`

When refreshed to candidate revision (132):

$ /snap/bin/sublime-text.subl 
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libX11.so.6)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libX11.so.6)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libXau.so.6)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libbsd.so.0)
/snap/sublime-text/132/opt/sublime_text/sublime_text: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /snap/sublime-text/132/usr/lib/x86_64-linux-gnu/libmd.so.0)

After reverting back to 122 it just works.

$ ls -la /snap/bin/sublime-text.subl 
lrwxrwxrwx 1 root root 13 lis 23 11:41 /snap/bin/sublime-text.subl -> /usr/bin/snap

**Comment by popey** [comment]
Ok, I've pushed 4152 (the previous, working release) to the stable channel while we debug this.

**Comment by popey** [comment]
Ok, I have reproduced this issue on a clean install of 20.04 with the snap from candidate.

**Comment by sergiusens** [comment]
Just to fill in, on:
```
sergiusens@cuivienen:~$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 23.10"
NAME="Ubuntu"
VERSION_ID="23.10"
VERSION="23.10 (Mantic Minotaur)"
VERSION_CODENAME=mantic
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=mantic
LOGO=ubuntu-logo
```

Both, rev 4152 and 4166 work fine
```
sergiusens@cuivienen:~$ snap install sublime-text --classic
sublime-text 4152 from Snapcrafters✪ installed
sergiusens@cuivienen:~$ sublime-text.subl 
sergiusens@cuivienen:~$ snap refresh sublime-text --edge
sublime-text (edge) 4166 from Snapcrafters✪ refreshed
sergiusens@cuivienen:~$ sublime-text.subl 
sergiusens@cuivienen:~$
```

**Comment by 8uben** [comment]
@popey, i've done:

```
~$ snap refresh sublime-text --channel=latest/candidate/fix-bug-47
sublime-text (candidate/fix-bug-47) 4166 от Snapcrafters✪ обновлён
~$ subl -v
Sublime Text Build 4166
```
after, i ran sublime-text.

Thank you!

P.S i have Kubuntu 20.04

**Comment by dafcioo** [comment]
> Locally, I have built a snap of 4166 after reverting the change to using `core22`, so my build uses the older `core20` configuration. This works fine in Ubuntu 20.04, and 23.10 where I've tested it. I've built it again in launchpad, and published to a short-lived test branch.
> 
> Please, @dafcioo (and any others affected) if you have a moment, please test this build.
> 
> `snap refresh sublime-text --channel=latest/candidate/fix-bug-47`
> 
> Many thanks.

Well done! Works for me :)

$ snap refresh sublime-text --channel=latest/candidate/fix-bug-47
sublime-text (candidate/fix-bug-47) 4166 from Snapcrafters✪ refreshed
$ /snap/bin/sublime-text.subl
$ subl -v
Sublime Text Build 4166

**Comment by popey** [comment]
Perfect, thanks for confirming. I've promoted revisions 134 (amd64) and 135 (arm64) to latest/stable, and closed all other channels for the moment—apologies for the drama. I'll start a new issue/thread to discuss how to resolve this.

**Comment by raphapaulino** [comment]
> snap refresh sublime-text --candidate

It worked for me, thank you @popey !

**Comment by nmondal** [comment]
Somehow w/o doing anything my sublime text started working. Not sure how the magic happened, but it happened.
Thank you everyone. Appreciated.

**Comment by popey** [comment]
@nmondal The :magic_wand: Magic :magic_wand: of automatic updates! :dancers:
