### ISSUE TITLE
[Enhancement]: Have previous version available for installation

### ISSUE THREAD

**Issue by dagbj** [snapcrafters/sublime-text#48]
### What changes would you like?

Make previous version, or more versions, available to install. Currently sublime-text does only provide latest version.

My problem is that this version fails on my installation, I filed a bug report. Testing reinstall for fixing the problem made `snap revert`   unavailable, so I'm stuck until an update is available or a way of installing an older version.
`
$ snap list sublime-text --all
Name          Version  Rev  Tracking       Publisher      Notes
sublime-text  4166     130  latest/stable  snapcrafters✪  classic
`

**Comment by jnsgruk** [comment]
Hey!

You can actually install a snap by revision by default now. Can you please try:

```
sudo snap install sublime-text --revision <working rev>
```

Thanks!

**Comment by jnsgruk** [comment]
Closing for now, we can reopen if the above doesn't solve the issue! Let me know!
