### ISSUE TITLE
Install instructions don't work

### ISSUE THREAD

**Issue by variadico** [snapcrafters/sublime-text#7]
Took the instructions from the readme.

```
$ snap install sublime-text-3 --classic
error: snap "sublime-text-3" not found
```

Did the name change or something?

**Comment by omkarnathsingh** [comment]
Try this "snap install sublime-text-3 --classic --candidate"

**Comment by AdilsonTorres** [comment]
Try:
` snap install sublime-text --classic`

**Comment by popey** [comment]
The name did indeed change. Thanks @AdilsonTorres !
